bismillah_bazar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('employee_management/', include('employee_management.urls')),

]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .views import manage_product, view_cart, add_to_cart, update_cart, remove_from_cart, clear_cart



urlpatterns = [
    path('', views.main_page, name='main_page'),  # Main page URL should come first
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),

    path('cart_/', view_cart, name='view_cart'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart/', update_cart, name='update_cart'),
    path('remove_from_cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', clear_cart, name='clear_cart'),

    path('process_order/', views.process_order, name='process_order'),
    path('product_list/', views.product_list, name='product_list'),
    path('signup/', views.customer_signup, name='signup'),
    path('accounts/login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='logout_success'), name='logout'),
    path('logout_success/', TemplateView.as_view(template_name='registration/logout.html'), name='logout_success'),

    # Password reset URLs with custom templates in the "registration" folder
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path('add_product/', views.add_product, name='add_product'),
    path('add_file/', views.add_file, name='add_file'),
    path('manage_product/<int:product_id>/', manage_product, name='manage_product'),
    
    path('payment_success/', views.payment_success, name='payment_success'),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Department(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Position(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    city = models.CharField(max_length=255)

    DHAKA = 'DH'
    CHITTAGONG = 'CG'
    RAJSHAHI = 'RA'
    KHULNA = 'KH'
    BARISAL = 'BA'
    SYLHET = 'SY'
    RANGPUR = 'RN'

    DIVISION_CHOICES = [
        (DHAKA, 'Dhaka'),
        (CHITTAGONG, 'Chittagong'),
        (RAJSHAHI, 'Rajshahi'),
        (KHULNA, 'Khulna'),
        (BARISAL, 'Barisal'),
        (SYLHET, 'Sylhet'),
        (RANGPUR, 'Rangpur'),
    ]

    DIVISION_DEFAULT = CHITTAGONG

    division = models.CharField(max_length=2, choices=DIVISION_CHOICES, default=DIVISION_DEFAULT)

    CUSTOMER = 'customer'
    EMPLOYEE = 'employee'
    MANAGER = 'manager'
    SUPERVISOR = 'supervisor'
    HR = 'hr'
    COO = 'coo'

    ROLE_CHOICES = [
        (CUSTOMER, 'Customer'),
        (EMPLOYEE, 'Employee'),
        (MANAGER, 'Manager'),
        (SUPERVISOR, 'Supervisor'),
        (HR, 'Human Resources'),
        (COO, 'Chief Operating Officer'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=CUSTOMER)

    def save(self, *args, **kwargs):
        if not self.division:
            self.division = self.DIVISION_DEFAULT
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

from django.utils import timezone

class Employee(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    employee_id = models.AutoField(primary_key=True)    
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, blank=True)
    date_of_hiring = models.DateField(default=timezone.now)
    
    # Updated Fields
    EMPLOYEE_TYPE_CHOICES = [
        ('Part-Time', 'Part-Time'),
        ('Full-Time', 'Full-Time'),
        ('Contract', 'Contract'),
        ('Temporary', 'Temporary'),
    ]
    employee_type = models.CharField(max_length=20, choices=EMPLOYEE_TYPE_CHOICES, null=True)
    
    # If part-time, availability for each day of the week
    availability_monday_start = models.TimeField(null=True, blank=True)
    availability_monday_finish = models.TimeField(null=True, blank=True)
    
    availability_tuesday_start = models.TimeField(null=True, blank=True)
    availability_tuesday_finish = models.TimeField(null=True, blank=True)
    
    availability_wednesday_start = models.TimeField(null=True, blank=True)
    availability_wednesday_finish = models.TimeField(null=True, blank=True)
    
    availability_thursday_start = models.TimeField(null=True, blank=True)
    availability_thursday_finish = models.TimeField(null=True, blank=True)
    
    availability_friday_start = models.TimeField(null=True, blank=True)
    availability_friday_finish = models.TimeField(null=True, blank=True)
    
    availability_saturday_start = models.TimeField(null=True, blank=True)
    availability_saturday_finish = models.TimeField(null=True, blank=True)
    
    availability_sunday_start = models.TimeField(null=True, blank=True)
    availability_sunday_finish = models.TimeField(null=True, blank=True)
    
    hourly_rate = models.DecimalField(max_digits=10, decimal_places=2, default=120)
    
    SHIFT_CHOICES = [
        ('Morning', 'Morning'),
        ('Evening', 'Evening'),
    ]
    shift = models.CharField(max_length=20, choices=SHIFT_CHOICES, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.get_employee_type_display()}"
    
    @staticmethod
    def generate_employee_id():
        last_employee = Employee.objects.order_by('-employee_id').first()
        if last_employee:
            return last_employee.employee_id + 1
        else:
            return 10000001



class Manager(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Manager - {self.user.username}"

class Supervisor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Supervisor - {self.user.username}"

class HR(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f"HR - {self.user.username}"

class COO(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f"COO - {self.user.username}"

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=10, null=True, blank=True)
    color = models.CharField(max_length=20, null=True, blank=True)
    image = models.ImageField(upload_to='product_images/', null=True, blank=True)

    def __str__(self):
        return self.name

store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Product
from .cart import Cart
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib import messages
from django.views.generic import TemplateView

def main_page(request):
    return render(request, 'store/main.html')

def product_list(request):
    products = Product.objects.all()
    return render(request, 'store/product_list.html', {'products': products, 'title': 'Product List'})

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'store/product_detail.html', {'product': product})

def process_order(request):
    # Implement order processing logic here
    # Capture customer information, handle payment, update inventory, etc.
    # After processing, you may want to clear the cart and show an order confirmation page
    return render(request, 'store/order_confirmation.html')




def customer_signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.success(request, f"Account created successfully. Welcome, {user.username}!")
            return redirect('main_page')
        else:
            # Handle form validation errors
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"Error in {field}: {error}")

    else:
        form = CustomUserCreationForm()

    return render(request, 'registration/signup.html', {'form': form})






def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, f"Welcome back, {user.username}!")
            return redirect('main_page')
        else:
            # Handle form validation errors
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"Error in {field}: {error}")
    else:
        form = CustomAuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})



def user_logout(request):
    logout(request)
    messages.success(request, "You have been successfully logged out. Come back soon!")
    return redirect('logout_success')

class LogoutSuccessView(TemplateView):
    template_name = 'registration/logout.html'




# views.py

# views.py
from django.shortcuts import render, redirect
from .forms import ProductForm

def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            # Handle the form data to add a single product
            # For example, you might save the form data to the database
            form.save()
            # Add a success message
            messages.success(request, 'Product added successfully.')
            return redirect('product_list')  # Redirect to the product list page
        else:
            # Print form errors for debugging
            print(form.errors)
            # Add an error message
            messages.error(request, 'Error adding the product. Please check the form.')
    else:
        form = ProductForm()

    return render(request, 'store/add_product.html', {'form': form})


# views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .forms import CSVImportForm
from .models import Product

def add_file(request):
    if request.method == 'POST':
        form = CSVImportForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.cleaned_data['file']
            # Handle the CSV file upload logic
            num_products = form.handle_uploaded_file(file)

            # Add a success message
            messages.success(request, f'Successfully imported {num_products} products from the CSV file.')

            return redirect('product_list')  # Redirect to the product list page
    else:
        form = CSVImportForm()

    return render(request, 'store/add_file.html', {'form': form})




# views.py
from django.contrib.auth.decorators import user_passes_test

@user_passes_test(lambda u: u.is_staff, login_url='login')
def manage_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product details updated successfully.')
            return redirect('product_detail', product_id=product.id)
        else:
            messages.error(request, 'Error updating product details. Please check the form.')
    else:
        form = ProductForm(instance=product)

    return render(request, 'store/manage_product.html', {'form': form, 'product': product})



from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Product
from .cart import Cart
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib import messages
from django.views.generic import TemplateView

# ... (Your existing imports)

def view_cart(request):
    cart = Cart(request)
    return render(request, 'store/shopping_cart.html', {'cart': cart})

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart = Cart(request)

    # Get the requested quantity (default to 1 if not provided)
    quantity = int(request.POST.get('quantity', 1))

    # # Check if the requested quantity is available
    # if quantity > product.quantity_in_stock:
    #     messages.error(request, f"Sorry, only {product.quantity_in_stock} units are available.")
    #     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    cart.add(product, quantity)
    messages.success(request, f"{product.name} added to the cart.")
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def update_cart(request):
    if request.method == 'POST':
        product_id = request.POST.get('product_id')
        quantity = int(request.POST.get('quantity', 1))  # Default to 1 if quantity is not provided

        if product_id:
            product = get_object_or_404(Product, pk=product_id)
            cart = Cart(request)
            cart.update(product, quantity)

    return redirect('view_cart')

def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    cart = Cart(request)
    cart.remove(product)
    messages.success(request, f"{product.name} removed from the cart.")
    return redirect('view_cart')

def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    messages.success(request, "Cart cleared.")
    return redirect('view_cart')




from django.shortcuts import render

def payment_success(request):
    return render(request, 'store/payment_success.html')

store/templates/store/add_file.html
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-1">
        <h2 class="display-5 text-center with-underline">Add a File Instead</h2>
    </div>
    <hr>
{% endblock %}

{% block content %}
    <!-- Import CSV Form -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="file">CSV File:</label>
            <input type="file" name="file" accept=".csv" required>
        </div>
        <button type="submit" class="btn btn-primary">Import Products</button>
    </form>
{% endblock %}

store/templates/store/add_product.html
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-1">
        <h2 class="display-5 text-center with-underline">Add a New Service</h2>
    </div>
    <hr>
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <!-- Add Single Product Form -->
        <form method="post" enctype="multipart/form-data" class="mb-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Service Name:</label>
                <input type="text" class="form-control" name="name" id="id_name" required>
            </div>
            <div class="form-group">
                <label for="id_description">Service Description:</label>
                <textarea class="form-control" name="description" id="id_description" required></textarea>
            </div>
            <div class="form-group">
                <label for="id_price">Price:</label>
                <input type="number" class="form-control" name="price" id="id_price" step="0.01" required>
            </div>
            <div class="form-group">
                <label for="id_image">Product Image:</label>
                <input type="file" class="form-control-file" name="image" id="id_image" accept="image/*">
            </div>
            <button type="submit" class="btn btn-primary">Add Product</button>
        </form>
    </div>
{% endblock %}

store/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content_title %}
    <div class="container mt-1">
        <h2 class="display-5 text-center">Checkout</h2>
        <hr>
    </div>
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div id="payment-errors" class="alert alert-danger" role="alert" style="display: none;"></div>

        <form id="payment-form">
            {% csrf_token %}

            <div id="card-element"></div>
            <div id="card-errors" role="alert"></div>
            <button id="submit-button" class="btn btn-primary mt-3">Pay Now</button>
            <input type="hidden" name="client_secret" value="{{ client_secret }}">
        </form>

        <ul>
            {% for item in items %}
                <li>{{ item.quantity }} x {{ item.price_data.product_data.name }}</li>
            {% endfor %}
        </ul>

        <p>Total Amount: ${{ cart.get_total_price|floatformat:2 }}</p>
    </div>

    <script src="https://js.stripe.com/v3/" defer></script>
    <script src="{% static 'js/stripe.js' %}" defer></script>
    <script>
        var stripe = Stripe('pk_test_51OGvLoBfoLOjTuhJWWx8cnFFSDuJNXTaymUEe8fBWLcjZNbYtGDCw400Sf76gmKHQzeqlrGVYfyHW0lc82jy5BJ100VIfvEmBc');
        var elements = stripe.elements();
        var card = elements.create('card');
        card.mount('#card-element');

        card.addEventListener('change', function (event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function (event) {
            event.preventDefault();
            document.getElementById('submit-button').disabled = true;

            stripe.confirmCardPayment('{{ client_secret }}', {
                payment_method: {
                    card: card,
                }
            }).then(function (result) {
                if (result.error) {
                    displayError.textContent = result.error.message;
                    document.getElementById('submit-button').disabled = false;
                } else {
                    if (result.paymentIntent.status === 'succeeded') {
                        window.location.href = '/payment_success/';
                    }
                }
            });
        });
    </script>
{% endblock %}

store/templates/store/main.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- Logo and Introduction Section -->
    <div class="container text-center mt-4">
        {% comment %} <img src="{% static 'images/laundry_logo.jpg' %}" alt="Shantipurshal Laundry Service Logo" class="img-fluid" width="500" height="400"> {% endcomment %}
        <h1>Welcome to Shantipurshal Laundry Service</h1>
        <p>Your trusted partner for premium laundry services. Fast, efficient, and reliable!</p>
        <img src="{% static 'images/brand_image.jpg' %}" alt="Laundry Facility" class="img-fluid" width="600" height="300">
    </div>

    <!-- Updated Navigation Links -->
    <div class="text-center mt-3">
        <a href="#" class="btn btn-link">Wash & Fold</a> |
        <a href="#" class="btn btn-link">Dry Cleaning</a> |
        <a href="{% url 'product_list' %}" class="btn btn-link">Special Services</a> |
        <a href="#" class="btn btn-link">Pickup & Delivery</a>
    </div>
    
    

    <!-- Improved Search Bar -->
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Search for laundry services or products" aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-primary" type="button">Search</button>
        </div>
    </div>

    <!-- Special Offers Section -->
    <div class="container mt-4">
        <h2>Special Offers</h2>
        <p>Discover our exclusive offers on laundry services. Limited time only!</p>
        <!-- Add your offer content here -->
    </div>

    <!-- Discounts Section -->
    <div class="container mt-4">
        <h2>Discounts</h2>
        <p>Save more with our ongoing discounts. Check out our budget-friendly options!</p>
        <!-- Add your discount content here -->
    </div>

    <!-- Popular Section -->
    <div class="container mt-4">
        <h2>Popular Services</h2>
        <p>Explore our most popular laundry services loved by our customers.</p>
        <!-- Add your popular content here -->
    </div>
{% endblock %}

store/templates/store/manage_product.html
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-1">
        <h2 class="display-5 text-center with-underline">Manage Product</h2>
    </div>
    <hr>
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow">
                <div class="card-body">
                    <!-- Manage Product Form -->
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label for="{{ form.category.id_for_label }}" class="font-weight-bold">Category:</label>
                            {{ form.category }}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.name.id_for_label }}" class="font-weight-bold">Product Name:</label>
                            {{ form.name }}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.description.id_for_label }}" class="font-weight-bold">Product Description:</label>
                            {{ form.description }}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.price.id_for_label }}" class="font-weight-bold">Price:</label>
                            {{ form.price }}
                        </div>


                        <div class="form-group">
                            <label for="{{ form.image.id_for_label }}" class="font-weight-bold">Product Image:</label>
                            {{ form.image }}
                        </div>

                        {% comment %} <div class="form-group">
                            <label for="{{ form.size.id_for_label }}" class="font-weight-bold">Size:</label>
                            {{ form.size }}
                        </div>

                        <div class="form-group">
                            <label for="{{ form.color.id_for_label }}" class="font-weight-bold">Color:</label>
                            {{ form.color }}
                        </div> {% endcomment %}

                        <!-- Additional Images -->
                        {% comment %} <div class="form-group">
                            <label class="font-weight-bold">Additional Images:</label>
                            {% for image_form in form.additional_images %}
                                {{ image_form }}
                            {% endfor %}
                        </div> {% endcomment %}

                        <!-- Add more form fields as needed -->

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary btn-lg">Update Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

store/templates/store/payment_success.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4 text-center">
        <h2 class="text-success">Payment Successful!</h2>
        <p>Thank you for your purchase. Your order has been successfully processed.</p>
        <!-- Add any additional information or links as needed -->
    </div>
{% endblock %}

store/templates/store/product_detail.html
<!-- Updated product_detail.html with enhanced styling -->
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-4">
        <h2 class="display-4 text-center">{{ product.name }}</h2>
        <hr>
    </div>
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid rounded product-image" width="300" height="200">
                {% else %}
                    <p>No image available</p>
                {% endif %}
            </div>
            <div class="col-md-6">
                <div class="product-info">
                    <h2 class="font-weight-bold">{{ product.name }}</h2>
                    <p class="price">Price: <b>৳{{ product.price }}</b></p>
                    {% comment %} <p class="stock">In Stock: <b>{{ product.quantity_in_stock }}</b></p> {% endcomment %}

                    {% if user.is_authenticated and user.is_staff %}
                        <a href="{% url 'manage_product' product_id=product.id %}" class="btn btn-primary btn-lg">Manage Service</a>
                    {% else %}
                        <form method="post" action="{% url 'add_to_cart' product.id %}" class="mt-3">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="quantity">Quantity:</label>
                                <input type="number" name="quantity" value="1" min="1" max="{{ product.quantity_in_stock }}" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-success btn-lg">Add to Cart</button>
                        </form>
                    {% endif %}
                    <hr>
                    <p class="lead">{{ product.description }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

store/templates/store/product_list.html
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-4">
        <h2 class="display-5 text-center">Our Services</h2>
        <hr class="my-4">
    </div>
{% endblock %}

{% block content %}
    <style>
        /* Custom CSS for setting a fixed height and width for product images without cropping */
        .product-image-container {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 200px; /* Set the desired height */
        }

        .product-image {
            width: 300px; /* Set the desired width */
            height: 100%; /* Maintain aspect ratio */
            object-fit: contain; /* Maintain aspect ratio and fit within the container */
        }
    </style>

    <div class="container mt-4">
        <div class="row">
            {% for product in products %}
                <div class="col-md-6 mb-4">
                    <div class="card h-100">
                        {% if product.image and product.image.url %}
                            <div class="product-image-container">
                                <img src="{{ product.image.url }}" class="card-img-top product-image mx-auto" alt="{{ product.name }}">
                            </div>
                        {% else %}
                            <!-- Placeholder image or default content when the image doesn't exist -->
                            <div class="text-center">
                                <p>No Image Available</p>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="card-text">Price: ৳{{ product.price }} per item</p>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                {% if user.is_authenticated and user.is_staff %}
                                    <a href="{% url 'manage_product' product_id=product.id %}" class="btn btn-primary btn">Manage Service</a>
                                {% else %}
                                    <form method="post" action="{% url 'add_to_cart' product.id %}">
                                        {% csrf_token %}
                                        <div class="input-group">
                                            <input type="number" name="quantity" value="1" min="1" max="{{ product.quantity_in_stock }}" class="form-control">
                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-success">Add to Cart</button>
                                            </div>
                                        </div>
                                    </form>
                                {% endif %}
                                <a href="{% url 'product_detail' product.id %}" class="btn btn-primary">View Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}