bismillah_bazar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('employee_management/', include('employee_management.urls')),

]

employee_management/urls.py
# employee_management/urls.py
from django.urls import path
from .views import (
    employee_list,
    employee_detail,
    employee_create,
    employee_update,
    employee_delete,
    update_availability
)

urlpatterns = [
    path('employees/', employee_list, name='employee_list'),
    path('employees/<int:employee_id>/', employee_detail, name='employee_detail'),
    path('employees/create/', employee_create, name='employee_create'),
    path('employees/<int:employee_id>/update/', employee_update, name='employee_update'),
    path('employees/<int:employee_id>/delete/', employee_delete, name='employee_delete'),
    path('update_availability/<int:employee_id>/', update_availability, name='update_availability'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .views import manage_product, view_cart, add_to_cart, update_cart, remove_from_cart, clear_cart



urlpatterns = [
    path('', views.main_page, name='main_page'),  # Main page URL should come first
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),

    path('cart_/', view_cart, name='view_cart'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update_cart/', update_cart, name='update_cart'),
    path('remove_from_cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', clear_cart, name='clear_cart'),

    path('process_order/', views.process_order, name='process_order'),
    path('product_list/', views.product_list, name='product_list'),
    path('signup/', views.customer_signup, name='signup'),
    path('accounts/login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='logout_success'), name='logout'),
    path('logout_success/', TemplateView.as_view(template_name='registration/logout.html'), name='logout_success'),

    # Password reset URLs with custom templates in the "registration" folder
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    path('add_product/', views.add_product, name='add_product'),
    path('add_file/', views.add_file, name='add_file'),
    path('manage_product/<int:product_id>/', manage_product, name='manage_product'),
    
    path('payment_success/', views.payment_success, name='payment_success'),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee_management/models.py
from django.db import models

# Create your models here.

store/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Department(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Position(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    city = models.CharField(max_length=255)

    DHAKA = 'DH'
    CHITTAGONG = 'CG'
    RAJSHAHI = 'RA'
    KHULNA = 'KH'
    BARISAL = 'BA'
    SYLHET = 'SY'
    RANGPUR = 'RN'

    DIVISION_CHOICES = [
        (DHAKA, 'Dhaka'),
        (CHITTAGONG, 'Chittagong'),
        (RAJSHAHI, 'Rajshahi'),
        (KHULNA, 'Khulna'),
        (BARISAL, 'Barisal'),
        (SYLHET, 'Sylhet'),
        (RANGPUR, 'Rangpur'),
    ]

    DIVISION_DEFAULT = CHITTAGONG

    division = models.CharField(max_length=2, choices=DIVISION_CHOICES, default=DIVISION_DEFAULT)

    CUSTOMER = 'customer'
    EMPLOYEE = 'employee'
    MANAGER = 'manager'
    SUPERVISOR = 'supervisor'
    HR = 'hr'
    COO = 'coo'

    ROLE_CHOICES = [
        (CUSTOMER, 'Customer'),
        (EMPLOYEE, 'Employee'),
        (MANAGER, 'Manager'),
        (SUPERVISOR, 'Supervisor'),
        (HR, 'Human Resources'),
        (COO, 'Chief Operating Officer'),
    ]

    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=CUSTOMER)

    def save(self, *args, **kwargs):
        if not self.division:
            self.division = self.DIVISION_DEFAULT
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

from django.utils import timezone

class Employee(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    employee_id = models.AutoField(primary_key=True)    
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    position = models.ForeignKey(Position, on_delete=models.SET_NULL, null=True, blank=True)
    date_of_hiring = models.DateField(default=timezone.now)
    
    # Updated Fields
    EMPLOYEE_TYPE_CHOICES = [
        ('Part-Time', 'Part-Time'),
        ('Full-Time', 'Full-Time'),
        ('Contract', 'Contract'),
        ('Temporary', 'Temporary'),
    ]
    employee_type = models.CharField(max_length=20, choices=EMPLOYEE_TYPE_CHOICES, null=True)
    
    # If part-time, availability for each day of the week
    availability_monday_start = models.TimeField(null=True, blank=True)
    availability_monday_finish = models.TimeField(null=True, blank=True)
    
    availability_tuesday_start = models.TimeField(null=True, blank=True)
    availability_tuesday_finish = models.TimeField(null=True, blank=True)
    
    availability_wednesday_start = models.TimeField(null=True, blank=True)
    availability_wednesday_finish = models.TimeField(null=True, blank=True)
    
    availability_thursday_start = models.TimeField(null=True, blank=True)
    availability_thursday_finish = models.TimeField(null=True, blank=True)
    
    availability_friday_start = models.TimeField(null=True, blank=True)
    availability_friday_finish = models.TimeField(null=True, blank=True)
    
    availability_saturday_start = models.TimeField(null=True, blank=True)
    availability_saturday_finish = models.TimeField(null=True, blank=True)
    
    availability_sunday_start = models.TimeField(null=True, blank=True)
    availability_sunday_finish = models.TimeField(null=True, blank=True)
    
    hourly_rate = models.DecimalField(max_digits=10, decimal_places=2, default=120)
    
    SHIFT_CHOICES = [
        ('Morning', 'Morning'),
        ('Evening', 'Evening'),
    ]
    shift = models.CharField(max_length=20, choices=SHIFT_CHOICES, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.get_employee_type_display()}"
    
    @staticmethod
    def generate_employee_id():
        last_employee = Employee.objects.order_by('-employee_id').first()
        if last_employee:
            return last_employee.employee_id + 1
        else:
            return 10000001



class Manager(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Manager - {self.user.username}"

class Supervisor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Supervisor - {self.user.username}"

class HR(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f"HR - {self.user.username}"

class COO(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return f"COO - {self.user.username}"

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=10, null=True, blank=True)
    color = models.CharField(max_length=20, null=True, blank=True)
    image = models.ImageField(upload_to='product_images/', null=True, blank=True)

    def __str__(self):
        return self.name

employee_management/forms.py
# employee_management/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from store.models import Employee, CustomUser
from django.forms.widgets import DateInput, TimeInput


class CustomUserSignUpForm(UserCreationForm):
    phone_number = forms.CharField(max_length=15, required=True)
    city = forms.CharField(max_length=255, required=True)
    division = forms.ChoiceField(choices=CustomUser.DIVISION_CHOICES, initial=CustomUser.DIVISION_DEFAULT)
    role = forms.ChoiceField(choices=CustomUser.ROLE_CHOICES, initial=CustomUser.CUSTOMER)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'phone_number', 'city', 'division', 'role']


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['employee_type', 'department', 'position', 'date_of_hiring', 'hourly_rate', 'shift']
        widgets = {
            'date_of_hiring': DateInput(attrs={'type': 'date'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Set the initial value for hourly_rate
        self.fields['hourly_rate'].initial = 120  # Replace 120 with your default value



# employee_management/forms.py
from django import forms
from store.models import Employee
from django.forms.widgets import TimeInput

class AvailabilityForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = [
            'availability_monday_start', 'availability_monday_finish',
            'availability_tuesday_start', 'availability_tuesday_finish',
            'availability_wednesday_start', 'availability_wednesday_finish',
            'availability_thursday_start', 'availability_thursday_finish',
            'availability_friday_start', 'availability_friday_finish',
            'availability_saturday_start', 'availability_saturday_finish',
            'availability_sunday_start', 'availability_sunday_finish',
        ]
        widgets = {
            'availability_monday_start': TimeInput(attrs={'type': 'time'}),
            'availability_monday_finish': TimeInput(attrs={'type': 'time'}),
            'availability_tuesday_start': TimeInput(attrs={'type': 'time'}),
            'availability_tuesday_finish': TimeInput(attrs={'type': 'time'}),
            'availability_wednesday_start': TimeInput(attrs={'type': 'time'}),
            'availability_wednesday_finish': TimeInput(attrs={'type': 'time'}),
            'availability_thursday_start': TimeInput(attrs={'type': 'time'}),
            'availability_thursday_finish': TimeInput(attrs={'type': 'time'}),
            'availability_friday_start': TimeInput(attrs={'type': 'time'}),
            'availability_friday_finish': TimeInput(attrs={'type': 'time'}),
            'availability_saturday_start': TimeInput(attrs={'type': 'time'}),
            'availability_saturday_finish': TimeInput(attrs={'type': 'time'}),
            'availability_sunday_start': TimeInput(attrs={'type': 'time'}),
            'availability_sunday_finish': TimeInput(attrs={'type': 'time'}),
        }

employee_management/views.py
# employee_management/views.py
from django.shortcuts import render, get_object_or_404, redirect
from store.models import Employee
from django.contrib.auth import login
from .forms import CustomUserSignUpForm, EmployeeForm, AvailabilityForm

def employee_list(request):
    employees = Employee.objects.all()
    for employee in employees:
        print(f"id: {employee.employee_id}, Type: {employee.get_employee_type_display()}")
    return render(request, 'employee_management/employee_list.html', {'employees': employees})


def employee_detail(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)
    return render(request, 'employee_management/employee_detail.html', {'user': employee.user, 'employee': employee})

from django.contrib import messages

def employee_create(request):
    print('Entering employee_create')
    if request.method == 'POST':
        user_form = CustomUserSignUpForm(request.POST)

        if user_form.is_valid():
            user = user_form.save()
            
            # Generate employee_id
            employee_id = Employee.generate_employee_id()

            # Create Employee with generated employee_id
            Employee.objects.create(user=user, employee_id=employee_id)

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')

            # Add a success message
            messages.success(request, 'Employee signed up successfully!')

            return redirect('employee_list')  # Redirect to the employee list page or another page
    else:
        user_form = CustomUserSignUpForm()

    return render(request, 'employee_management/employee_form.html', {'user_form': user_form})


def employee_update(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)

    if request.method == 'POST':
        employee_form = EmployeeForm(request.POST, instance=employee)

        employee_form.save()
        return redirect('employee_list')  # Redirect to the employee list page or another page
    else:
        employee_form = EmployeeForm(instance=employee)

    return render(request, 'employee_management/employee_update.html', { 'employee_form': employee_form, 'employee_id': employee_id})


def employee_delete(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)
    employee.delete()
    return redirect('employee_list')




def update_availability(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)

    if request.method == 'POST':
        availability_form = AvailabilityForm(request.POST, instance=employee)
        if availability_form.is_valid():
            availability_form.save()
            return redirect('employee_list')  # Redirect to the employee list page or another page
    else:
        availability_form = AvailabilityForm(instance=employee)

    return render(request, 'employee_management/update_availability.html', {'availability_form': availability_form, 'employee_id': employee_id})

employee_management/templates/employee_management/employee_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content_title %}
    <div class="container mt-4">
        <h2 class="display-5 text-center">Employee Details</h2>
        <hr class="my-4">
    </div>
{% endblock %}

{% block content %}
    <!-- Employee Details page -->
    <div class="row justify-content-center">
        <div class="col-md-8">

            <!-- Display Employee Information -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title text-center mb-4">Employee Information</h5>
                    <dl class="row">
                        <dt class="col-sm-4">Username:</dt>
                        <dd class="col-sm-8">{{ user.username }}</dd>

                        <dt class="col-sm-4">Employee ID:</dt>
                        <dd class="col-sm-8">{{ employee.employee_id }}</dd>

                        <dt class="col-sm-4">Email:</dt>
                        <dd class="col-sm-8">{{ user.email }}</dd>

                        <dt class="col-sm-4">Phone Number:</dt>
                        <dd class="col-sm-8">{{ user.phone_number }}</dd>

                        <dt class="col-sm-4">Department:</dt>
                        <dd class="col-sm-8">{{ employee.department }}</dd>

                        <dt class="col-sm-4">Position:</dt>
                        <dd class="col-sm-8">{{ employee.position }}</dd>

                        <dt class="col-sm-4">Date of Hiring:</dt>
                        <dd class="col-sm-8">{{ employee.date_of_hiring }}</dd>

                        <dt class="col-sm-4">Employee Type:</dt>
                        <dd class="col-sm-8">{{ employee.get_employee_type_display }}</dd>

                        <dt class="col-sm-4">Hourly Rate:</dt>
                        <dd class="col-sm-8">{{ employee.hourly_rate }}</dd>

                        <dt class="col-sm-4">Shift:</dt>
                        <dd class="col-sm-8">{{ employee.get_shift_display }}</dd>

                        <!-- Add more fields as needed -->

                    </dl>
                </div>
            </div>

            <!-- Display Employee Availability Information -->
            <div class="card mt-4">
                <div class="card-body">
                    <h5 class="card-title text-center mb-4">Availability Information</h5>
                    <dl class="row">
                        <!-- Monday -->
                        <dt class="col-sm-4">Monday:</dt>
                        <dd class="col-sm-8">
                            {% if employee.availability_monday_start and employee.availability_monday_finish %}
                                {{ employee.availability_monday_start }} - {{ employee.availability_monday_finish }}
                            {% else %}
                                Not Available
                            {% endif %}
                        </dd>

                        <!-- Tuesday -->
                        <dt class="col-sm-4">Tuesday:</dt>
                        <dd class="col-sm-8">
                            {% if employee.availability_tuesday_start and employee.availability_tuesday_finish %}
                                {{ employee.availability_tuesday_start }} - {{ employee.availability_tuesday_finish }}
                            {% else %}
                                Not Available
                            {% endif %}
                        </dd>

                        <!-- Wednesday -->
                        <dt class="col-sm-4">Wednesday:</dt>
                        <dd class="col-sm-8">
                            {% if employee.availability_wednesday_start and employee.availability_wednesday_finish %}
                                {{ employee.availability_wednesday_start }} - {{ employee.availability_wednesday_finish }}
                            {% else %}
                                Not Available
                            {% endif %}
                        </dd>

                        <!-- Thursday -->
                        <dt class="col-sm-4">Thursday:</dt>
                        <dd class="col-sm-8">
                            {% if employee.availability_thursday_start and employee.availability_thursday_finish %}
                                {{ employee.availability_thursday_start }} - {{ employee.availability_thursday_finish }}
                            {% else %}
                                Not Available
                            {% endif %}
                        </dd>

                        <!-- Friday -->
                        <dt class="col-sm-4">Friday:</dt>
                        <dd class="col-sm-8">
                            {% if employee.availability_friday_start and employee.availability_friday_finish %}
                                {{ employee.availability_friday_start }} - {{ employee.availability_friday_finish }}
                            {% else %}
                                Not Available
                            {% endif %}
                        </dd>

                        <!-- Saturday -->
                        <dt class="col-sm-4">Saturday:</dt>
                        <dd class="col-sm-8">
                            {% if employee.availability_saturday_start and employee.availability_saturday_finish %}
                                {{ employee.availability_saturday_start }} - {{ employee.availability_saturday_finish }}
                            {% else %}
                                Not Available
                            {% endif %}
                        </dd>

                        <!-- Sunday -->
                        <dt class="col-sm-4">Sunday:</dt>
                        <dd class="col-sm-8">
                            {% if employee.availability_sunday_start and employee.availability_sunday_finish %}
                                {{ employee.availability_sunday_start }} - {{ employee.availability_sunday_finish }}
                            {% else %}
                                Not Available
                            {% endif %}
                        </dd>
                    </dl>
                </div>
            </div>

            <!-- Link to Employee Update (conditionally displayed) -->
            {% if user.is_authenticated %}
                {% if user.role == 'employee' %}
                    <div class="text-center mt-4">
                        <a href="{% url 'update_availability' user.employee.employee_id %}" class="btn btn-primary">Update Availability</a>
                    </div>
                {% endif %}

            {% elif user.is_staff %}
                    <div class="text-center mt-4">
                        <a href="{% url 'employee_update' user.employee.employee_id %}" class="btn btn-primary">Update Employee Information</a>
                        <a href="{% url 'update_availability' user.employee.employee_id %}" class="btn btn-primary">Update Availability</a>
                    </div>
            {% endif %}
        </div>
    </div>

    <!-- Print Favicon -->
    <div class="text-right mt-4">
        <a href="javascript:void(0)" onclick="printAvailability()">
            <img src="{% static 'images/print.png' %}" alt="Print" width="30" height="30">
        </a>
    </div>

    <script>
        function printAvailability() {
            window.print();
        }
    </script>
{% endblock %}

employee_management/templates/employee_management/employee_form.html
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-1">
        <h2 class="display-5 text-center">Employee Sign Up</h2>
        <hr>
    </div>
{% endblock %}

{% block content %}
    <!-- Sign Up page -->
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" action="{% url 'employee_create' %}" class="mt-4">
                {% csrf_token %}

                <!-- Username -->
                <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" name="{{ user_form.username.name }}" class="form-control" required>
                </div>

                <!-- Email -->
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" name="{{ user_form.email.name }}" class="form-control" required>
                </div>

                <!-- Password -->
                <div class="form-group">
                    <label for="password1">Password:</label>
                    <input type="password" name="{{ user_form.password1.name }}" class="form-control" required>
                </div>

                <!-- Confirm Password -->
                <div class="form-group">
                    <label for="password2">Confirm Password:</label>
                    <input type="password" name="{{ user_form.password2.name }}" class="form-control" required>
                </div>

                <!-- Phone Number -->
                <div class="form-group">
                    <label for="phone_number">Phone Number:</label>
                    <input type="text" name="{{ user_form.phone_number.name }}" class="form-control" required>
                </div>

                <!-- Division -->
                <div class="form-group">
                    <label for="division">Division:</label>
                    <select name="{{ user_form.division.name }}" class="form-control" required>
                        <option value="" disabled selected>Select Division</option>
                        {% for code, name in user_form.division.field.choices %}
                            <option value="{{ code }}" {% if code == user_form.division.value %}selected{% endif %}>{{ name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- City -->
                <div class="form-group">
                    <label for="city">City:</label>
                    <input type="text" name="{{ user_form.city.name }}" class="form-control" value="Cumilla" required>
                </div>

                <!-- Role -->
                <div class="form-group">
                    <label for="role">Role:</label>
                    <select name="{{ user_form.role.name }}" class="form-control" required>
                        <option value="" disabled selected>Select Role</option>
                        {% for code, name in user_form.role.field.choices %}
                            <option value="{{ code }}" {% if code == user_form.role.value %}selected{% endif %}>{{ name }}</option>
                        {% endfor %}
                    </select>
                </div>


                <button type="submit" class="btn btn-success">Sign Up as Employee</button>
            </form>
        </div>
    </div>
{% endblock %}

employee_management/templates/employee_management/employee_list.html
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-4">
        <h2 class="display-5 text-center">Employee List</h2>
        <hr class="my-4">
    </div>
{% endblock %}

{% block content %}
    <div class="container mt-4">
        {% if employees %}
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Employee ID</th>
                            <th scope="col">Employment Type</th>
                            <th scope="col">Department</th>
                            <th scope="col">Position</th>
                            <th scope="col">Date of Hiring</th>
                            <th scope="col">Hourly Rate</th>
                            <th scope="col">Shift</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employees %}
                            <tr>
                                <td>{{ employee.employee_id }}</td>
                                <td>{{ employee.employee_type }}</td>
                                <td>{{ employee.department }}</td>
                                <td>{{ employee.position }}</td>
                                <td>{{ employee.date_of_hiring }}</td>
                                <td>{{ employee.hourly_rate }}</td>
                                <td>{{ employee.shift }}</td>
                                <td>
                                    {% if employee.employee_id %}
                                        <div class="btn-group" role="group" aria-label="Employee Actions">
                                            <a href="{% url 'employee_detail' employee.employee_id %}" class="btn btn-primary btn-sm">View Details</a>
                                            <a href="{% url 'employee_update' employee.employee_id %}" class="btn btn-warning btn-sm">Update</a>
                                            <a href="{% url 'update_availability' employee_id=employee.employee_id %}" class="btn btn-info btn-sm">Update Availability</a>
                                        </div>
                                    {% else %}
                                        <p class="text-danger">Employee ID is empty.</p>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p class="lead">No employees available.</p>
        {% endif %}
    </div>
{% endblock %}

employee_management/templates/employee_management/employee_update.html
{% extends 'base.html' %}

{% block content_title %}
    <div class="container mt-1">
        <h2 class="display-5 text-center">Update Employee Information</h2>
        <hr>
    </div>
{% endblock %}

{% block content %}
    <!-- Update Employee page -->
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form method="post" action="{% url 'employee_update' employee_id=employee_id %}" class="mt-4">
                {% csrf_token %}
                
                <!-- Fields from Employee model -->
                {{ employee_form.as_p }}

                <button type="submit" class="btn btn-success">Update Employee Information</button>
            </form>
        </div>
    </div>
{% endblock %}